export default {
    LOAD: 'LOAD',
    BUSCAR_DADOS_SETOR: 'BUSCAR_DADOS_SETOR',
    BUSCAR_DADOS_CATEGORIA: 'BUSCAR_DADOS_CATEGORIA',
    BUSCAR_DADOS_CATEGORIA_FILTER: 'BUSCAR_DADOS_CATEGORIA_FILTER',

}