export default {
    LOAD_AUTH: 'LOAD_AUTH',
    GUARDAR_TOKEN: 'GUARDAR_TOKEN',
    REMOVER_TOKEN: 'REMOVER_TOKEN',
    GUARDAR_DATA_LOGIN_USER: 'GUARDAR_DATA_LOGIN_USER',
    GUARDAR_PAPEL_USUARIO: 'GUARDAR_PAPEL_USUARIO'
}