export default {
    LOAD: 'LOAD',
    BUSCAR_PAPEIS: 'BUSCAR_PAPEIS',
    BUSCAR_PERMISSOES: 'BUSCAR_PERMISSOES',
    BUSCAR_SETOR: 'BUSCAR_SETOR',
    BUSCAR_CATEGORIA: 'BUSCAR_CATEGORIA',
    BUSCAR_FORMULARIOS: 'BUSCAR_FORMULARIOS',
    BUSCAR_CAMPOS_FORMULARIOS: 'BUSCAR_CAMPOS_FORMULARIOS',
    BUSCAR_STATUS_TICKET: 'BUSCAR_STATUS_TICKET',
    BUSCAR_USUARIOS: 'BUSCAR_USUARIOS',
    BUSCAR_MENUS: 'BUSCAR_MENUS',
    BUSCAR_SUB_MENU: 'BUSCAR_SUB_MENU'
}