export default {
    LOAD: 'LOAD',
    BUSCAR_MEUS_TICKETS: 'BUSCAR_MEUS_TICKETS',
    BUSCAR_MEU_SETOR: 'BUSCAR_MEU_SETOR',
    BUSCAR_MINHAS_CATEGORIAS: 'BUSCAR_MINHAS_CATEGORIAS',
    BUSCAR_INTERACOES_TICKETS: 'BUSCAR_INTERACOES_TICKETS',
    BUSCAR_TICKETS_SETOR: 'BUSCAR_TICKETS_SETOR',
}